/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import javax.swing.JRadioButton;
import so.FCFS_FIFO;
import so.SJF;

/**
 *
 * @author Denise
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupProcessos = new javax.swing.ButtonGroup();
        jButtonExecutar = new javax.swing.JButton();
        Processos = new javax.swing.JLabel();
        jRadioButtonFIFO = new javax.swing.JRadioButton();
        jRadioButtonSJF = new javax.swing.JRadioButton();
        jButtonSair = new javax.swing.JButton();
        jLabelEscalonamento = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escalonamento de Processos");
        setPreferredSize(new java.awt.Dimension(805, 480));
        getContentPane().setLayout(null);

        jButtonExecutar.setBackground(new java.awt.Color(204, 0, 51));
        jButtonExecutar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExecutar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExecutar.setText("Executar");
        jButtonExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExecutar);
        jButtonExecutar.setBounds(10, 180, 100, 30);

        Processos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Processos.setText("Processos");
        getContentPane().add(Processos);
        Processos.setBounds(10, 80, 100, 30);

        buttonGroupProcessos.add(jRadioButtonFIFO);
        jRadioButtonFIFO.setText("FIFO");
        jRadioButtonFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFIFOActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFIFO);
        jRadioButtonFIFO.setBounds(10, 150, 100, 23);

        buttonGroupProcessos.add(jRadioButtonSJF);
        jRadioButtonSJF.setSelected(true);
        jRadioButtonSJF.setText("SJF");
        jRadioButtonSJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSJFActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSJF);
        jRadioButtonSJF.setBounds(10, 110, 100, 23);

        jButtonSair.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(10, 210, 100, 30);

        jLabelEscalonamento.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabelEscalonamento.setText("Escalonamento de Processos: SJF - FIFO");
        getContentPane().add(jLabelEscalonamento);
        jLabelEscalonamento.setBounds(10, 10, 430, 50);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/escalonamento.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 830, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jRadioButtonSJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSJFActionPerformed
          
    }//GEN-LAST:event_jRadioButtonSJFActionPerformed

    private void jButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarActionPerformed
        if(jRadioButtonSJF.isSelected()){
            //executar o SJF
            SJF sjf = new SJF();
            String[] vazio = new String[1]; 
            sjf.main(vazio);
        }else{
            //executar o FCFS_FIFO
            FCFS_FIFO fifo = new FCFS_FIFO();
            String[] vazio = new String[1]; 
            fifo.main(vazio);//executar FIFO
            
        }        
    }//GEN-LAST:event_jButtonExecutarActionPerformed

    private void jRadioButtonFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFIFOActionPerformed
        
    }//GEN-LAST:event_jRadioButtonFIFOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Processos;
    private javax.swing.ButtonGroup buttonGroupProcessos;
    private javax.swing.JButton jButtonExecutar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelEscalonamento;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JRadioButton jRadioButtonFIFO;
    private javax.swing.JRadioButton jRadioButtonSJF;
    // End of variables declaration//GEN-END:variables

    
}
